### ISSUE TITLE
Can't use ScreenMazer with this version of macOS

### ISSUE THREAD

**Issue by brij1234** [dado3212/ScreenMazer#1]
I'm on 10.13.6
![image](https://user-images.githubusercontent.com/9251787/44181675-fd69a100-a0d0-11e8-8732-76f59f486d3b.png)

**Comment by dado3212** [comment]
I'm ON 10.13.6.  Hmm.

**Comment by dado3212** [comment]
Can you try again using this link: https://github.com/dado3212/ScreenMazer/raw/master/ScreenMazer.zip

**Comment by brij1234** [comment]
That worked
