### ISSUE TITLE
Preview is broken on macOS Mojave (10.14.3)

### ISSUE THREAD

**Issue by Wandmalfarbe** [dado3212/ScreenMazer#3]
<img width="780" alt="screenshot 2019-02-23 14 41 50" src="https://user-images.githubusercontent.com/17237627/53287215-35852700-3779-11e9-8afb-c692b6df6760.png">

As you can see in the screenshot, the preview is broken on macOS Mojave (10.14.3). The screensaver works when I click preview but I can't quit or close it without hitting the power button.

**Comment by dominikznidar** [comment]
@Wandmalfarbe I managed to close it with CTRL key

**Comment by dado3212** [comment]
It's working again on 10.14.5.  Marking this as closed, but lmk if you're still running into it.

**Comment by philippelatulippe** [comment]
Hi! Nice screensaver! I have the same issue on a fresh install of 10.14.6. The preview doesn't work (though there is no error message, just a black rectangle) and it is very difficult to exit the screensaver. It can take a minute of keyboard, mouse and trackpad movement before the password dialog shows up.
